DROP TABLE IF EXISTS race;

CREATE TABLE race (
    id TINYINT(1) UNSIGNED NOT NULL PRIMARY KEY,
    name CHAR(6) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE job (
    id TINYINT(1) UNSIGNED NOT NULL PRIMARY KEY,
    name CHAR(6) NOT NULL
) ENGINE=InnoDB;
