DROP TABLE IF EXISTS clan_note;
DROP TABLE IF EXISTS clan;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(32),
    email VARCHAR(100),
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE clan (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INTEGER UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT clan_user_fk FOREIGN KEY (user_id) REFERENCES user (id)
) ENGINE=InnoDB;

CREATE TABLE clan_note (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INTEGER UNSIGNED NOT NULL,
    clan_id INTEGER UNSIGNED NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note TEXT NOT NULL,
    CONSTRAINT clan_note_user_fk FOREIGN KEY (user_id) REFERENCES user (id),
    CONSTRAINT clan_note_clan_fk FOREIGN KEY (clan_id) REFERENCES clan (id)
) ENGINE=InnoDB;
